# Pandas Basics



The table has one row for each album and several columns

- **artist** - Name of the artist
- **album** - Name of the album
- **released_year** - Year the album was released
- **length_min_sec** - Length of the album (hours,minutes,seconds)
- **genre** - Genre of the album
- **music_recording_sales_millions** - Music recording sales (millions in USD) on [SONG://DATABASE](http://www.song-database.com/)
- **claimed_sales_millions** - Album's claimed sales (millions in USD) on [SONG://DATABASE](http://www.song-database.com/)
- **date_released** - Date on which the album was released
- **soundtrack** - Indicates if the album is the movie soundtrack (Y) or (N)
- **rating_of_friends** - Indicates the rating from your friends from 1 to 10
<br>

You can see the dataset here:

<font size="1">
<table font-size:xx-small style="width:85%">
  <tr>
    <th>Artist</th>
    <th>Album</th> 
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th> 
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td> 
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td> 
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td> 
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td> 
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td> 
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td> 
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td> 
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td> 
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<a id="ref1"></a>
<h2 align=center> Importing Data </h2>

We can import the libraries  or dependency like Pandas  using the following command:

In [1]:
import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allows you to work with data is a dataframe. Let's go through the process to go from a comma separated values (**.csv** ) file to a dataframe. This variable **csv_path** stores the path of the  **.csv** ,that is  used as an argument to the **read_csv** function. The result is stored in the object ** df**, this is a common short form used for a variable referring to a Pandas dataframe.

In [3]:
pd.read_sql

<function pandas.io.sql.read_sql(sql, con, index_col: 'str | list[str] | None' = None, coerce_float: 'bool' = True, params=None, parse_dates=None, columns: 'list[str] | None' = None, chunksize: 'int | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>, dtype: 'DtypeArg | None' = None) -> 'DataFrame | Iterator[DataFrame]'>

In [4]:
df=pd.read_csv('top_selling_albums.csv')

In [5]:
type(df)

pandas.core.frame.DataFrame

We can use the method **head()** to examine the first five rows of a dataframe:

In [6]:
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

We can use the method **tail()** to examine the last five rows of a dataframe:

In [7]:
df.tail()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

We can use the attribute **shape** to examine the number of rows and columns of a dataframe:

In [8]:
df.shape

(8, 10)

The process for loading an excel file is similar, we use the path of the excel file and the function **read_excel**. The result is a data frame as before:

In [ ]:
#dependency  needed to install file checking package existance with in environment
#!pip install xlrd

In [9]:
df = pd.read_excel('top_selling_albums.xlsx')
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

We can access the column "Length" and assign it a new dataframe 'x':

In [11]:
x=df[['Length']]
x

     Length
0  00:42:19
1   0:42:11
2   0:42:49
3   0:57:44
4   0:46:33
5   0:43:08
6  01:15:54
7   0:40:01

 The process is shown in the figure:

<img src = "https://ibm.box.com/shared/static/bz800py5ui4w0kpb0k09lq3k5oegop5v.png" width = 750, align = "center"></a>

 <a id="ref2"></a>
<h2 align=center> Viewing Data and Accessing Data </h2>

You can also assign the value to a series, you can think of a Pandas series as a 1-D dataframe. Just use one bracket:

In [12]:
x=df['Length']
type(x)

pandas.core.series.Series

In [13]:
x

0    00:42:19
1     0:42:11
2     0:42:49
3     0:57:44
4     0:46:33
5     0:43:08
6    01:15:54
7     0:40:01
Name: Length, dtype: object

You can also assign different columns, for example, we can assign the column 'Artist':

In [15]:
newvar=df[['Released.1']]
newvar

  Released.1
0 1982-11-30
1 1980-07-25
2 1973-03-01
3 1992-11-17
4 1977-10-21
5 1976-02-17
6 1977-11-15
7 1977-02-04

In [16]:
x=df[['Artist']]
type(x)

pandas.core.frame.DataFrame

#### Assign the variable 'q' to the dataframe that is made up of the column 'Rating':

In [18]:
#write code here
q=df[['Rating']]
q

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

In [19]:
You can do the same thing for multiple columns; we just put the dataframe name, in this case, **df**, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

SyntaxError: invalid syntax (725923309.py, line 1)

In [20]:
y=df[['Length','Artist','Genre']]
y

     Length           Artist                        Genre
0  00:42:19  Michael Jackson               pop, rock, R&B
1   0:42:11            AC/DC                    hard rock
2   0:42:49       Pink Floyd             progressive rock
3   0:57:44  Whitney Houston               R&B, soul, pop
4   0:46:33        Meat Loaf  hard rock, progressive rock
5   0:43:08           Eagles   rock, soft rock, folk rock
6  01:15:54         Bee Gees                        disco
7   0:40:01    Fleetwood Mac                    soft rock

The process is shown in the figure:

<img src = "https://ibm.box.com/shared/static/dh9duk3ucuhmmmbixa6ugac6g384m5sq.png" width = 1100, align = "center"></a>

In [21]:
df[['Album','Released','Length']]

                             Album  Released    Length
0                         Thriller      1982  00:42:19
1                    Back in Black      1980   0:42:11
2        The Dark Side of the Moon      1973   0:42:49
3                    The Bodyguard      1992   0:57:44
4                  Bat Out of Hell      1977   0:46:33
5  Their Greatest Hits (1971-1975)      1976   0:43:08
6             Saturday Night Fever      1977  01:15:54
7                          Rumours      1977   0:40:01

#### Assign the variable 'q' to the dataframe that is made up of the column 'Released' and 'Artist':

In [22]:
q=df[['Released','Artist']]
q

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

One way to access unique elements is the 'iloc' method, where you can access the 1st row and first column as follows :

In [24]:
df.iloc[0,0:2]

Artist    Michael Jackson
Album            Thriller
Name: 0, dtype: object

Notice something? A series is returned

Let's convert it to table form

In [25]:
df.iloc[0:2,0:6]

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions)
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1

 You can access the 1st 2 rows as follows:

In [26]:
df.iloc[0:2]

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5

You can access columns with rows as well:

In [27]:
df.iloc[0:2,0:2]

            Artist          Album
0  Michael Jackson       Thriller
1            AC/DC  Back in Black

There is another method call 'loc' which uses names of row and column indexes.
Notice that 'iloc' was using row and column index to access values

In [28]:
df.loc[0:2,['Album']]

                       Album
0                   Thriller
1              Back in Black
2  The Dark Side of the Moon

Access multiple columns by 'loc'

In [29]:
df.loc[0:2,['Album','Length']]

                       Album    Length
0                   Thriller  00:42:19
1              Back in Black   0:42:11
2  The Dark Side of the Moon   0:42:49

#### Access the 4th to 6th row:

Trying with iloc it would be

#### Access 5th and rows after 5th with columns starting from Artist till Length

Using iloc

## Adding Column

In [30]:
df['New Artist'] = df['Artist']

In [31]:
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating,New Artist
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0,Michael Jackson
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5,AC/DC
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0,Pink Floyd
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5,Whitney Houston
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0,Meat Loaf

## Droping Column

In [32]:
df.drop(['New Artist'], axis=1, inplace=True)

In [33]:
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

## Object Type of each column

In [34]:
df.dtypes

Artist                                      object
Album                                       object
Released                                     int64
Length                                      object
Genre                                       object
Music Recording Sales (millions)           float64
Claimed Sales (millions)                     int64
Released.1                          datetime64[ns]
Soundtrack                                  object
Rating                                     float64
dtype: object

## Null values check in Data Frame

In [35]:
df.isnull()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,True,False

In [36]:
df.isnull().sum()

Artist                              0
Album                               0
Released                            0
Length                              0
Genre                               0
Music Recording Sales (millions)    0
Claimed Sales (millions)            0
Released.1                          0
Soundtrack                          6
Rating                              0
dtype: int64

## Summary Statistics

In [37]:
df.describe()

,Released,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Rating
count,8.000000,8.000000,8.000000,8,8.000000
mean,1979.250000,28.125000,46.125000,1979-10-20 21:00:00,8.250000
min,1973.000000,20.600000,40.000000,1973-03-01 00:00:00,6.500000
25%,1976.750000,23.300000,41.500000,1976-11-07 18:00:00,7.375000
50%,1977.000000,26.750000,43.500000,1977-11-02 12:00:00,8.250000
75%,1980.500000,28.975000,46.250000,1981-02-24 12:00:00,9.125000
max,1992.000000,46.000000,65.000000,1992-11-17 00:00:00,10.000000
std,5.800246,8.189322,8.271077,NaN,1.224745

In [38]:
df.describe(include='all')

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
count,8,8,8.000000,8,8,8.000000,8.000000,8,2,8.000000
unique,8,8,NaN,8,8,NaN,NaN,NaN,1,NaN
top,Michael Jackson,Thriller,NaN,00:42:19,"pop, rock, R&B",NaN,NaN,NaN,Y,NaN
freq,1,1,NaN,1,1,NaN,NaN,NaN,2,NaN
mean,NaN,NaN,1979.250000,NaN,NaN,28.125000,46.125000,1979-10-20 21:00:00,NaN,8.250000
min,NaN,NaN,1973.000000,NaN,NaN,20.600000,40.000000,1973-03-01 00:00:00,NaN,6.500000
25%,NaN,NaN,1976.750000,NaN,NaN,23.300000,41.500000,1976-11-07 18:00:00,NaN,7.375000
50%,NaN,NaN,1977.000000,NaN,NaN,26.750000,43.500000,1977-11-02 12:00:00,NaN,8.250000
75%,NaN,NaN,1980.500000,NaN,NaN,28.975000,46.250000,1981-02-24 12:00:00,NaN,9.125000
max,NaN,NaN,1992.000000,NaN,NaN,46.000000,65.000000,1992-11-17 00:00:00,NaN,10.000000
std,NaN,NaN,5.800246,NaN,NaN,8.189322,8.271077,NaN,NaN,1.224745

## Querying a dataframe

Querying a database means finding some values based on certain conditions. For example you want to find out the albums having rating greater and equal to 9

In [39]:
soundtracks= df[df['Rating']>=9.0]

In [40]:
soundtracks

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0

Notice that in the above result all the columns are displayed. If you want to access a specific column, then you can use **loc** for that purpose.

In [41]:
soundtracks_album= df.loc[df['Rating']>=9.0, ['Album']]

In [42]:
soundtracks_album

                       Album
0                   Thriller
1              Back in Black
2  The Dark Side of the Moon

### Task

Find out the albums released during and after the year 1980

In [ ]:
# write code here

# Exercise

Import file **cars.csv** and show following:

    1.) Top five rows
    2.) Last five rows
    3.) No. of rows and columns
    4.) Access 100th to 130th row with any 3 columns
    5.) Object types of each column
    6.) Null values count in each column
    7.) Summary Statistics

In [46]:
#importing the file
df_cars=pd.read_csv('cars.csv')

In [ ]:
#top 5 rows

In [ ]:
#last 5 rows

In [ ]:
#Access 100th to 130th row with any 3 columns

In [ ]:
# object types of each column

In [ ]:
#Null values count in each column

In [ ]:
#Summary statistics

# Grouping

Grouping works similar to "group by" as in databases. Pandas also provides a "group by" function which serves the same purpose.

In [47]:
fuel_price=df_cars.groupby('fuel-type')['price'].mean()

In [48]:
fuel_price

fuel-type
diesel    15838.15000
gas       12916.40884
Name: price, dtype: float64

In [49]:
door_price=df_cars.groupby('num-of-doors')['price'].mean()

In [50]:
door_price

num-of-doors
four    13498.034783
two     12818.127907
Name: price, dtype: float64

In [51]:
group=df_cars.groupby(['fuel-type','num-of-doors'])['price'].mean().reset_index()

In [52]:
group

  fuel-type num-of-doors         price
0    diesel         four  16100.764706
1    diesel          two  14350.000000
2       gas         four  13046.540816
3       gas          two  12762.759036

### Task

Find the total price according to each body style.

Hint: use <code>sum()</code> instead of <code>mean</code>.

In [ ]:
# write the code here

# Pivoting and Melting

**Pivoting**

In [53]:
pivoted= pd.pivot_table(group,index='fuel-type',columns='num-of-doors', values='price',aggfunc='mean',fill_value=0)

In [54]:
pivoted

num-of-doors          four           two
fuel-type
diesel        16100.764706  14350.000000
gas           13046.540816  12762.759036

In [ ]:
new= pivoted.reset_index()

In [ ]:
new

**Melting**

In [ ]:
melted= pd.melt(new,id_vars='fuel-type', value_name='Mean Price')

In [ ]:
melted

In [55]:
engine_archive = sql.create_engine('mssql+pymssql://DS_PAK_NOR:'+'dummy_pass'+'@server_IP_Adress/Archive_UBER_Replica',poolclass=NullPool)
with engine_archive.connect() as conn:
    df_vehLocation = pd.read_sql_query("""select * from VehicleLocationLog where VehicleLastSyncedOn >= DATEADD(day,-7, GETDATE()) """, con=conn)
conn.close()
engine_archive.dispose()

NameError: name 'sql' is not defined